source "https://rubygems.org"

gem "jekyll", "4.2.2"
gem "jekyll-feed", "0.15.1"
gem "jekyll-seo-tag", "2.8.0"
gem "jekyll-sitemap", "1.4.0"
gem "kramdown", "2.4.0"
gem "kramdown-parser-gfm", "1.1.0"
gem "rouge", "~> 3.0"
gem "webrick", "1.8.1"