#!/usr/bin/env python3
"""Generate one page per subdomain from _data/hosts.yml.

THE RULE THIS SCRIPT ENFORCES
    _data/hosts.yml is the single source of truth. Every page under /hosts/,
    /artists/ and the per-subdomain directories is produced from it. Nothing
    about a host is written by hand anywhere, so the directory, the status
    report and the individual pages cannot drift apart.

WHAT IT WRITES
    artists/index.html            the artist category index
    artists/<slug>/index.html     one page per artist-category host
    <slug>/index.html             one page per every other host
    <slug>/index.html             for artists too, as a canonical pointer to
                                  /artists/<slug>/ so that EVERY host in the
                                  zone answers at /<slug>/, which is the
                                  address people actually type

IT IS IDEMPOTENT. Running it twice produces the same bytes. It will not clobber
a file it did not write: every generated file opens with the generator's
signature, and a file lacking that signature but present on disk is a hand-
edited page, which is reported and skipped rather than overwritten.

USAGE
    python scripts/build_host_pages.py            # write what changed
    python scripts/build_host_pages.py --check    # fail if anything is stale
    python scripts/build_host_pages.py --clean    # remove generated pages that
                                                  # no longer have a record
"""

from __future__ import annotations

import argparse
import os
import sys

try:
    import yaml
except ImportError:  # pragma: no cover
    sys.exit("PyYAML is required: python -m pip install pyyaml")

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA = os.path.join(ROOT, "_data", "hosts.yml")
SIGNATURE = "<!-- generated by scripts/build_host_pages.py from _data/hosts.yml; do not edit -->"

# Kept in step with the note in _layouts/host.html. A layout cannot declare
# these for its children (Jekyll puts a layout's front matter in `layout`, not
# in `page`), so every generated page carries them itself.
EXTRA_CSS = ["/assets/css/hosts.css"]
EXTRA_JS = ["/assets/js/hosts.js"]

# Order here is the order of the checkboxes on the directory. "broken-dns" first
# because a broken name is the failure that needs a certificate or a CNAME, and
# the one nobody notices until somebody tries to use the link.
STATUS_RANK = {"broken-dns": 0, "down": 1, "guarded": 2, "ok": 3}

ACTION_ROW = [
    (
        "Book a slot",
        "https://appointmentthing.com/openstageisland",
        "Free, rolling availability. The island takes the stage for no fee.",
    ),
    (
        "Island Discord",
        "https://discord.gg/Z38YQ6Xmbp",
        "Slot requests and set times go through here.",
    ),
    (
        "Teleport",
        "secondlife://Derwent/248/128/22",
        "Second Life viewer only. In a browser use the web map instead.",
    ),
    (
        "Web map",
        "https://maps.secondlife.com/secondlife/Derwent/248/128/22",
        "Works in any browser.",
    ),
    ("Timetable", "http://timetable.openstageis.land", "What is on this week."),
]


# ── helpers ──────────────────────────────────────────────────────────────────


def read_data():
    with open(DATA, encoding="utf-8") as fh:
        data = yaml.safe_load(fh)
    if not isinstance(data, dict) or "hosts" not in data or "categories" not in data:
        sys.exit("_data/hosts.yml has no `categories` / `hosts` keys")
    return data


def validate(data):
    """Fail loudly here rather than emitting 34 pages that are subtly wrong."""
    cats = data["categories"]
    seen = {}
    problems = []
    for i, h in enumerate(data["hosts"]):
        slug = h.get("slug")
        if not slug:
            problems.append("record %d has no slug" % i)
            continue
        if slug in seen:
            problems.append("duplicate slug %r (records %d and %d)" % (slug, seen[slug], i))
        seen[slug] = i
        if h.get("category") not in cats:
            problems.append("%s: category %r is not in categories:" % (slug, h.get("category")))
        if h.get("status") not in STATUS_RANK:
            problems.append(
                "%s: status %r is not one of %s" % (slug, h.get("status"), sorted(STATUS_RANK))
            )
        for key in ("title", "url", "type"):
            if not h.get(key):
                problems.append("%s: missing %s" % (slug, key))
    if problems:
        for p in problems:
            sys.stderr.write("hosts.yml: %s\n" % p)
        sys.exit(1)


def write_if_changed(path, body, mode="write"):
    """Returns 'unchanged' | 'written' | 'skipped' | 'stale'."""
    rel = os.path.relpath(path, ROOT)
    existing = None
    if os.path.exists(path):
        with open(path, encoding="utf-8", newline="") as fh:
            existing = fh.read()
        if existing == body:
            return "unchanged"
        if SIGNATURE not in existing:
            if mode == "check":
                return "skipped"
            sys.stderr.write("refusing to overwrite hand-edited %s\n" % rel)
            return "skipped"
    if mode == "check":
        return "stale"
    parent = os.path.dirname(path)
    if parent and not os.path.isdir(parent):
        os.makedirs(parent)
    with open(path, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(body)
    return "written"


def y_esc(text):
    """A YAML double-quoted scalar. Front matter only."""
    return '"' + str(text).replace("\\", "\\\\").replace('"', '\\"') + '"'


_HTML_ESCAPES = {"&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;"}


def h_esc(text):
    """HTML text and double-quoted attribute values.

    Escapes the ampersand FIRST. Doing it later would double-escape the entities
    this function itself introduces, which is the classic way an escaper eats
    its own output on the second pass.
    """
    out = str(text)
    for char, entity in _HTML_ESCAPES.items():
        out = out.replace(char, entity)
    return out


def front_matter(fields):
    lines = ["---"]
    for key, value in fields:
        lines.append("%s: %s" % (key, value))
    lines.append("---")
    return "\n".join(lines)


def sibling_paths(host, all_hosts):
    """Other hosts kept by the same organisational account."""
    return [
        h for h in all_hosts if h["slug"] != host["slug"] and h.get("owner") == host.get("owner")
    ]


def same_category(host, all_hosts):
    return [h for h in all_hosts if h["slug"] != host["slug"] and h["category"] == host["category"]]


def path_for(host):
    if host["category"] == "artists":
        return "/artists/%s/" % host["slug"]
    return "/%s/" % host["slug"]


def action_buttons():
    out = ['<ul class="host-actions">']
    for label, href, title in ACTION_ROW:
        klass = (
            ' class="host-action host-action--native"'
            if href.startswith("secondlife:")
            else ' class="host-action"'
        )
        rel = "" if href.startswith("secondlife:") else ' rel="noopener noreferrer"'
        out.append(
            '  <li><a%s href="%s"%s title="%s">%s</a></li>'
            % (klass, href, rel, h_esc(title), h_esc(label))
        )
    out.append("</ul>")
    return "\n".join(out)


# ── per-host body ────────────────────────────────────────────────────────────


def artist_body(host, all_hosts):
    art = host.get("artist", {})
    genres = art.get("genres") or []
    genre_line = " · ".join(genres) if genres else "Not stated yet."

    chips = []
    for g in genres:
        chips.append('<span class="pill pill--guarded">%s</span>' % h_esc(g))
    if art.get("bpm"):
        chips.append('<span class="pill pill--ok">%s BPM</span>' % h_esc(art["bpm"]))

    related = same_category(host, all_hosts)
    rel_html = "\n".join(
        '      <li><a class="host-action" href="/artists/%s/">'
        '<span aria-hidden="true">%s</span> %s</a></li>'
        % (h["slug"], h.get("symbol", ""), h_esc(h["title"]))
        for h in related
    )

    return """
<section aria-labelledby="deck-heading">
  <h2 id="deck-heading">The deck</h2>
  <div style="display: flex; flex-wrap: wrap; gap: 8px; margin-bottom: 14px;" aria-label="Genre and tempo">
    {chips}
  </div>
  <div class="waveform" aria-hidden="true"></div>
  <dl class="host-dl">
    <div class="host-dl-row">
      <dt>Genres</dt>
      <dd>{genres}</dd>
    </div>
    <div class="host-dl-row">
      <dt>Tempo</dt>
      <dd>{bpm}</dd>
    </div>
    <div class="host-dl-row">
      <dt>Style</dt>
      <dd>{style}</dd>
    </div>
    <div class="host-dl-row">
      <dt>Owner</dt>
      <dd>{owner}</dd>
    </div>
    <div class="host-dl-row">
      <dt>Canonical page</dt>
      <dd><code>/artists/{slug}/</code></dd>
    </div>
  </dl>
</section>

<section aria-labelledby="book-heading">
  <h2 id="book-heading">Book {title}</h2>
  <p>
    Taking a slot on the island stage is free and there is no fee at any point.
    The only requirement is a Second Life account, which is free to make.
  </p>
  {actions}
  <p class="swirl-blurb">
    Prefer to talk it through first? The island's Discord is where slots get
    agreed and where set times get settled.
  </p>
</section>

<section aria-labelledby="bio-heading">
  <h2 id="bio-heading">Bio</h2>
  <p>{intro}</p>
  <dl class="swirl-fields">
    <div class="swirl-field{bio_class}">
      <dt>One line</dt>
      <dd>{bio}</dd>
    </div>
    <div class="swirl-field swirl-field--empty">
      <dt>Longer bio</dt>
      <dd>What this artist is known for, in the words the artist would use.</dd>
    </div>
    <div class="swirl-field swirl-field--empty">
      <dt>Residency</dt>
      <dd>Which channel or stage this act is a regular on.</dd>
    </div>
    <div class="swirl-field swirl-field--empty">
      <dt>Links</dt>
      <dd>Mixes, releases, anything the artist wants pinned above the fold.</dd>
    </div>
    <div class="swirl-field swirl-field--empty">
      <dt>Contact</dt>
      <dd>How a promoter or a collaborator reaches this act.</dd>
    </div>
  </dl>
  <p class="swirl-blurb">
    The empty rows above are intentional. This page is finished the moment
    someone fills them in, and it is more useful half-written than
    half-invented — so nothing is filled in for them.
  </p>
</section>

<section aria-labelledby="more-heading">
  <h2 id="more-heading">More in this category</h2>
  <ul class="host-actions">
{related}
  </ul>
</section>
""".format(
        chips="\n    ".join(chips),
        genres=h_esc(genre_line),
        bpm=h_esc(art.get("bpm") or "Not stated yet."),
        style=h_esc(art.get("style") or "Not written yet."),
        owner=h_esc(host.get("owner") or "Unassigned"),
        slug=host["slug"],
        title=h_esc(host["title"]),
        actions=action_buttons(),
        intro=h_esc(host.get("intro") or ""),
        bio=h_esc(host.get("bio") or "Who this is, in one line."),
        bio_class="" if host.get("bio") else " swirl-field--empty",
        related=rel_html,
    )


def standard_body(host, all_hosts):
    note = ""
    if host.get("note"):
        note = '\n  <p class="swirl-blurb">%s</p>' % h_esc(" ".join(host["note"].split()))

    sibs = sibling_paths(host, all_hosts)
    sib_html = ""
    if sibs:
        items = "\n".join(
            '      <li><a class="host-action" href="%s">'
            '<span aria-hidden="true">%s</span> %s</a></li>'
            % (path_for(h), h.get("symbol", ""), h_esc(h["title"]))
            for h in sibs
        )
        sib_html = """
<section aria-labelledby="sibling-heading">
  <h2 id="sibling-heading">Also kept by %s</h2>
  <ul class="host-actions">
%s
  </ul>
</section>
""" % (h_esc(host.get("owner") or "this account"), items)

    return """
<section aria-labelledby="what-heading">
  <h2 id="what-heading">What lives here</h2>
  <p>{intro}</p>{note}
</section>

<section aria-labelledby="owner-heading">
  <h2 id="owner-heading">Who keeps it</h2>
  <dl class="host-dl">
    <div class="host-dl-row">
      <dt>Owner</dt>
      <dd>{owner}</dd>
    </div>
    <div class="host-dl-row">
      <dt>Zone type</dt>
      <dd><code>{type}</code></dd>
    </div>
    <div class="host-dl-row">
      <dt>Category</dt>
      <dd><a href="/hosts/#{category}">{category_title}</a></dd>
    </div>
    <div class="host-dl-row">
      <dt>Directory</dt>
      <dd><a href="/hosts/">All {total} hosts</a></dd>
    </div>
  </dl>
</section>

<section aria-labelledby="frame-heading">
  <h2 id="frame-heading">Frame</h2>
  <p>
    This page is a frame, not a finished article. Fill in the slots and it is
    done; leave them and it is still a correct directory entry.
  </p>
  <dl class="swirl-fields">
    <div class="swirl-field swirl-field--empty">
      <dt>Bio</dt>
      <dd>Who or what this record stands for.</dd>
    </div>
    <div class="swirl-field swirl-field--empty">
      <dt>Page info</dt>
      <dd>What is behind the link, and how often it changes.</dd>
    </div>
    <div class="swirl-field swirl-field--empty">
      <dt>Runbook</dt>
      <dd>What to do if this link dies — who to ask, which record to edit.</dd>
    </div>
  </dl>
</section>
{sib}""".format(
        intro=h_esc(host.get("intro") or ""),
        note=note,
        owner=h_esc(host.get("owner") or "Unassigned"),
        type=host.get("type", "URL"),
        category=host["category"],
        category_title=h_esc(HOST_CATEGORY_TITLES.get(host["category"], host["category"])),
        total=len(ALL_HOSTS),
        sib=sib_html,
    )


HOST_CATEGORY_TITLES = {}
ALL_HOSTS = []


def host_page(host, all_hosts):
    desc = host.get("blurb") or host.get("intro") or host["title"]
    path = path_for(host)
    fields = [
        ("layout", "host"),
        ("slug", y_esc(host["slug"])),
        ("title", y_esc("%s — %s" % (host["title"], host["slug"]))),
        ("description", y_esc(desc)),
        ("permalink", y_esc(path)),
    ]
    fm = front_matter(fields)
    css = "\n".join("  - %s" % c for c in EXTRA_CSS)
    js = "\n".join("  - %s" % j for j in EXTRA_JS)
    fm = fm.replace("---\n", "---\nextra_css:\n%s\nextra_js:\n%s\n" % (css, js), 1)

    if host["category"] == "artists":
        body = artist_body(host, all_hosts)
    else:
        body = standard_body(host, all_hosts)
    # Front matter must be byte 0 or Jekyll treats the whole file as static
    # HTML and never applies the layout. The signature therefore goes BELOW
    # the closing delimiter, where it still guards write_if_changed().
    return "%s\n%s\n\n%s\n%s\n" % (fm, SIGNATURE, body, SIGNATURE)


def alias_page(host, all_hosts):
    """The /<slug>/ pointer for a host whose real page lives at /artists/<slug>/."""
    target = path_for(host)
    fields = [
        ("layout", "default"),
        ("title", y_esc("%s — %s" % (host["title"], host["slug"]))),
        (
            "description",
            y_esc("%s. Canonical page: %s" % (host.get("blurb") or host["title"], target)),
        ),
        ("permalink", y_esc("/%s/" % host["slug"])),
        ("canonical", y_esc("https://frenzypenguin.media%s" % target)),
    ]
    fm = front_matter(fields)
    return """{fm}
{sig}

<div class="host-hero">
  <p class="host-kicker"><span aria-hidden="true">↪</span> Moved</p>
  <h1>{title}</h1>
  <p class="host-lede">
    <code>{slug}</code> is an artist record, so its page lives with the rest of
    the roster rather than at the top level.
  </p>

  <div class="raw raw--{status}">
    <div class="raw-head">
      <span>Canonical address</span>
      <span class="pill pill--{status}">{status_label}</span>
    </div>
    <code class="raw-value">{target}</code>
  </div>

  <ul class="host-actions">
    <li><a class="host-action host-action--primary" href="{target}">
      <span aria-hidden="true">{symbol}</span> Go to {title} &rarr;</a></li>
    <li><a class="host-action" href="/artists/">All artists</a></li>
    <li><a class="host-action" href="/hosts/">Host directory</a></li>
  </ul>
</div>

<div class="waveform" aria-hidden="true"></div>

<section aria-labelledby="why-heading">
  <h2 id="why-heading">Why there are two addresses</h2>
  <p>
    Every subdomain in the zone answers at <code>/&lt;slug&gt;/</code>, because
    that is what gets typed and what gets pasted into a message. Artist records
    are grouped under <a href="/artists/"><code>/artists/</code></a> so the
    roster reads as a roster. This page points at the canonical one and carries
    the same address in its <code>&lt;link rel="canonical"&gt;</code>, so search
    engines settle on a single answer.
  </p>
</section>
{sig}
""".format(
        sig=SIGNATURE,
        fm=fm,
        title=h_esc(host["title"]),
        slug=host["slug"],
        target=target,
        symbol=host.get("symbol", ""),
        status=host["status"] if host["status"] != "broken-dns" else "broken",
        status_label=STATUS_LABEL.get(host["status"], host["status"]),
    )


STATUS_LABEL = {
    "ok": "Live",
    "guarded": "Live (guarded)",
    "down": "Down",
    "broken-dns": "Broken DNS",
}


def artist_index(data):
    cats = data["categories"]
    cat = cats.get("artists", {})
    artists = [h for h in data["hosts"] if h["category"] == "artists"]
    artists.sort(key=lambda h: (STATUS_RANK.get(h["status"], 9), h["title"]))

    cards = []
    for h in artists:
        art = h.get("artist", {})
        chips = "".join(
            '<span class="pill pill--guarded">%s</span> ' % g for g in (art.get("genres") or [])
        )
        if art.get("bpm"):
            chips += '<span class="pill pill--ok">%s BPM</span>' % art["bpm"]
        cards.append(
            """    <article class="swirl" id="artidx-{slug}" data-swirl>
      <span class="swirl-halo" aria-hidden="true"></span>
      <button class="swirl-source" type="button" data-swirl-toggle
              aria-expanded="false" aria-controls="artidx-{slug}-card"
              title="Open the {title} card">
        <span aria-hidden="true">{symbol}</span>
      </button>
      <div class="swirl-card" id="artidx-{slug}-card">
        <div class="swirl-panel">
          <div class="swirl-head">
            <span class="swirl-symbol" aria-hidden="true">{symbol}</span>
            <div>
              <p class="swirl-title">{title}</p>
              <p class="swirl-slug">{slug}</p>
            </div>
          </div>
          <p><a class="host-action host-action--primary" href="/artists/{slug}/">{title} &nearr;</a></p>
          <p class="swirl-blurb">{blurb}</p>
          <p style="display: flex; flex-wrap: wrap; gap: 6px; margin: 0 0 10px;" aria-label="Genre and tempo">{chips}</p>
          <dl class="swirl-fields">
            <div class="swirl-field{bio_class}">
              <dt>Bio</dt>
              <dd>{bio}</dd>
            </div>
            <div class="swirl-field swirl-field--empty">
              <dt>Longer bio</dt>
              <dd>What this artist is known for.</dd>
            </div>
            <div class="swirl-field swirl-field--empty">
              <dt>Contact</dt>
              <dd>How a promoter reaches this act.</dd>
            </div>
          </dl>
          <div class="raw raw--{status}">
            <div class="raw-head"><span>Raw link</span>
              <span class="pill pill--{status}">{status_label}</span></div>
            <code class="raw-value">{raw}</code>
          </div>
        </div>
      </div>
    </article>""".format(
                slug=h["slug"],
                title=h_esc(h["title"]),
                symbol=h.get("symbol", ""),
                blurb=h_esc(h.get("blurb") or ""),
                chips=chips,
                bio_class="" if h.get("bio") else " swirl-field--empty",
                bio=h_esc(h.get("bio") or "Who this is, in one line."),
                status=h["status"] if h["status"] != "broken-dns" else "broken",
                status_label=STATUS_LABEL.get(h["status"], h["status"]),
                raw=h_esc(h.get("raw") or h["url"]),
            )
        )

    dead = [h for h in artists if h["status"] in ("down", "broken-dns")]

    return """---
layout: default
title: "Artists"
description: "Every artist and audio channel in the zone, with the raw link, a probe result, and a bio frame on each page."
permalink: /artists/
extra_css:
{css}
extra_js:
{js}
---

{sig}

<header class="host-hero" role="banner">
  <p class="host-kicker"><span aria-hidden="true">{symbol}</span> Category</p>
  <h1>{cat_title}</h1>
  <p class="host-lede">{tagline}</p>
  <p>{blurb}</p>

  <div style="display: flex; align-items: center; gap: 14px;" aria-hidden="true">
    <span class="eq"><span></span><span></span><span></span><span></span><span></span></span>
    <span class="platter"></span>
  </div>
  <div class="waveform" aria-hidden="true"></div>

  <ul class="host-actions">
    <li><a class="host-action host-action--join" href="https://appointmentthing.com/openstageisland"
            rel="noopener noreferrer" title="Book a slot on the stage — free, no fee">
      <span aria-hidden="true">+</span> Book a slot</a></li>
    <li><a class="host-action host-action--native" href="secondlife://Derwent/248/128/22"
            title="Second Life viewer only">
      <span aria-hidden="true">⤵</span> Teleport</a></li>
    <li><a class="host-action" href="https://maps.secondlife.com/secondlife/Derwent/248/130/22"
            rel="noopener noreferrer" title="Works in any browser">
      <span aria-hidden="true">🗺</span> Web map</a></li>
    <li><a class="host-action" href="https://discord.gg/Z38YQ6Xmbp"
            rel="noopener noreferrer" title="Slot requests and set times">
      <span aria-hidden="true">⛓</span> Island Discord</a></li>
    <li><a class="host-action" href="/hosts/">All {total} hosts</a></li>
  </ul>
</header>

<section class="host-group" aria-labelledby="roster-heading">
  <div class="host-group-head">
    <span class="host-group-symbol" aria-hidden="true">{symbol}</span>
    <h2 class="host-group-title" id="roster-heading">The roster</h2>
    <span class="host-group-tagline">{count} records &middot; broken first</span>
    <p class="host-group-blurb">
      Each disc opens its card. The card carries the raw link and the probe
      result; the page behind it carries the bio frame.
    </p>
  </div>
  <div class="host-grid">
{cards}
  </div>
</section>

<section aria-labelledby="take-heading">
  <h2 id="take-heading">Taking the stage</h2>
  <p>
    Playing on the island is free, and there is no fee at any point in the
    process. Register a Second Life account — also free — turn up, and claim a
    slot. Booking is a conversation on the Discord, not a payment.
  </p>
{actions}
  <p class="swirl-blurb">
    <strong>{dead_count} of these {dead_word} not answering.</strong> The pages
    still exist and still say what the address should be, because a roster that
    quietly drops a dead act is worse than one that shows the wound. What each
    one needs is written in its own page.
  </p>
</section>

<section aria-labelledby="whole-heading">
  <h2 id="whole-heading">The rest of the zone</h2>
  <p>
    Artists are one category of {total}. The others are grouped the same way in
    the full directory.
  </p>
  <ul class="host-actions">
    <li><a class="host-action" href="/hosts/#social">Social</a></li>
    <li><a class="host-action" href="/hosts/#commerce">Commerce</a></li>
    <li><a class="host-action" href="/hosts/#stage">Stage</a></li>
    <li><a class="host-action" href="/hosts/#web">Web</a></li>
    <li><a class="host-action host-action--primary" href="/hosts/">Host directory</a></li>
  </ul>
</section>

{sig}
""".format(
        sig=SIGNATURE,
        css="\n".join("  - %s" % c for c in EXTRA_CSS),
        js="\n".join("  - %s" % j for j in EXTRA_JS),
        symbol=cat.get("symbol", "🎛"),
        cat_title=h_esc(cat.get("title", "Artists")),
        tagline=h_esc(cat.get("tagline", "")),
        blurb=h_esc(cat.get("blurb", "")),
        count=len(artists),
        total=len(data["hosts"]),
        cards="\n".join(cards),
        actions=action_buttons(),
        dead_count=len(dead),
        dead_word="entry is" if len(dead) == 1 else "entries are",
    )


# ── main ─────────────────────────────────────────────────────────────────────


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument(
        "--check",
        action="store_true",
        help="exit non-zero if any generated page is missing or stale",
    )
    ap.add_argument(
        "--clean", action="store_true", help="delete generated pages whose record has gone away"
    )
    args = ap.parse_args()
    mode = "check" if args.check else "write"

    data = read_data()
    validate(data)

    global HOST_CATEGORY_TITLES, ALL_HOSTS
    HOST_CATEGORY_TITLES = {k: v.get("title", k) for k, v in data["categories"].items()}
    ALL_HOSTS = data["hosts"]

    targets = {}  # abspath -> body
    wanted_dirs = set()

    targets[os.path.join(ROOT, "artists", "index.html")] = artist_index(data)

    for h in data["hosts"]:
        if h["category"] == "artists":
            p = os.path.join(ROOT, "artists", h["slug"], "index.html")
            targets[p] = host_page(h, data["hosts"])
            wanted_dirs.add(os.path.join(ROOT, h["slug"]))
            targets[os.path.join(ROOT, h["slug"], "index.html")] = alias_page(h, data["hosts"])
        else:
            p = os.path.join(ROOT, h["slug"], "index.html")
            targets[p] = host_page(h, data["hosts"])
            wanted_dirs.add(p)

    results = {}
    for path in sorted(targets):
        results[os.path.relpath(path, ROOT)] = write_if_changed(path, targets[path], mode)

    if args.clean:
        for d in sorted(wanted_dirs):
            if not os.path.isdir(d):
                continue
            for name in os.listdir(d):
                p = os.path.join(d, name)
                if not os.path.isfile(p):
                    continue
                with open(p, encoding="utf-8", newline="") as fh:
                    head = fh.read(400)
                if SIGNATURE not in head:
                    continue
                if os.path.abspath(p) in targets:
                    continue
                if mode == "check":
                    results[os.path.relpath(p, ROOT)] = "orphan"
                else:
                    os.remove(p)
                    results[os.path.relpath(p, ROOT)] = "removed"

    counts = {}
    for state in results.values():
        counts[state] = counts.get(state, 0) + 1

    for rel in sorted(results):
        if results[rel] != "unchanged":
            print("%-9s %s" % (results[rel], rel))

    print(
        "\n%d host records -> %d pages: %s"
        % (
            len(data["hosts"]),
            len(targets),
            ", ".join("%d %s" % (v, k) for k, v in sorted(counts.items())),
        )
    )

    bad = [r for r, s in results.items() if s in ("stale", "orphan")]
    if bad:
        sys.stderr.write(
            "\n%s\n"
            % (
                "out of date: " + ", ".join(bad)
                if args.check
                else "generation failed: " + ", ".join(bad)
            )
        )
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
